[2022-12-04 11:42:03,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:10:00+00:00 [queued]>
[2022-12-04 11:42:03,909] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:10:00+00:00 [queued]>
[2022-12-04 11:42:03,910] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:42:03,910] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 11:42:03,911] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:42:04,055] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-04 18:10:00+00:00
[2022-12-04 11:42:04,076] {standard_task_runner.py:52} INFO - Started process 14135 to run task
[2022-12-04 11:42:04,110] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-04T18:10:00+00:00', '--job-id', '5580', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpihskkkwm', '--error-file', '/tmp/tmpzq9h8y98']
[2022-12-04 11:42:04,140] {standard_task_runner.py:77} INFO - Job 5580: Subtask local_to_gcs_task
[2022-12-04 11:42:04,424] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:10:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 11:42:04,732] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-04T18:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-04T18:10:00+00:00
[2022-12-04 11:42:05,648] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 11:42:05,700] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221104T181000, start_date=20221204T114203, end_date=20221204T114205
[2022-12-04 11:42:05,882] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 11:42:06,053] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
