[2022-12-04 13:06:00,836] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-06T17:10:00+00:00 [queued]>
[2022-12-04 13:06:00,856] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-06T17:10:00+00:00 [queued]>
[2022-12-04 13:06:00,856] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 13:06:00,857] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 13:06:00,857] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 13:06:00,893] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-11-06 17:10:00+00:00
[2022-12-04 13:06:00,901] {standard_task_runner.py:52} INFO - Started process 2537 to run task
[2022-12-04 13:06:00,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-11-06T17:10:00+00:00', '--job-id', '7236', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmps7aymuzz', '--error-file', '/tmp/tmp6m7m59ct']
[2022-12-04 13:06:00,911] {standard_task_runner.py:77} INFO - Job 7236: Subtask save_to_csv
[2022-12-04 13:06:01,022] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-11-06T17:10:00+00:00 [running]> on host 7a020590adae
[2022-12-04 13:06:01,128] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T17:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-06T17:10:00+00:00
[2022-12-04 13:06:01,180] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 13:06:01,208] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221106T171000, start_date=20221204T130600, end_date=20221204T130601
[2022-12-04 13:06:01,281] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 13:06:01,773] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
