[2022-12-04 09:29:16,897] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-30T05:50:00+00:00 [queued]>
[2022-12-04 09:29:17,021] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-30T05:50:00+00:00 [queued]>
[2022-12-04 09:29:17,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 09:29:17,062] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 09:29:17,078] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 09:29:17,205] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-30 05:50:00+00:00
[2022-12-04 09:29:17,232] {standard_task_runner.py:52} INFO - Started process 1037 to run task
[2022-12-04 09:29:17,267] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-30T05:50:00+00:00', '--job-id', '2436', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpgv8uagk1', '--error-file', '/tmp/tmp65vil92e']
[2022-12-04 09:29:17,270] {standard_task_runner.py:77} INFO - Job 2436: Subtask save_to_csv
[2022-12-04 09:29:17,556] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-30T05:50:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 09:29:18,330] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-30T05:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-30T05:50:00+00:00
[2022-12-04 09:29:18,475] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 09:29:18,525] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221030T055000, start_date=20221204T092916, end_date=20221204T092918
[2022-12-04 09:29:18,660] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 09:29:18,867] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
