[2022-12-04 02:48:14,866] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-12-04 02:48:15,369] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-12-04 02:48:15,426] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 02:48:15,432] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 02:48:15,433] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 02:48:15,781] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-27 00:00:00+00:00
[2022-12-04 02:48:15,892] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2022-12-04 02:48:15,899] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-27T00:00:00+00:00', '--job-id', '623', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpr287h0b9', '--error-file', '/tmp/tmp3rheubqz']
[2022-12-04 02:48:15,980] {standard_task_runner.py:77} INFO - Job 623: Subtask save_to_csv
[2022-12-04 02:48:17,401] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T00:00:00+00:00 [running]> on host 422c372562ce
[2022-12-04 02:48:18,427] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T00:00:00+00:00
[2022-12-04 02:48:18,846] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 02:48:18,953] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221027T000000, start_date=20221204T024814, end_date=20221204T024818
[2022-12-04 02:48:19,131] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 02:48:20,122] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
