[2022-12-04 10:42:49,521] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-01T17:40:00+00:00 [queued]>
[2022-12-04 10:42:49,590] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-01T17:40:00+00:00 [queued]>
[2022-12-04 10:42:49,603] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:42:49,605] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:42:49,605] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:42:49,659] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-01 17:40:00+00:00
[2022-12-04 10:42:49,676] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-01T17:40:00+00:00', '--job-id', '3805', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmphgcxa5qj', '--error-file', '/tmp/tmp4_ew5p2a']
[2022-12-04 10:42:49,682] {standard_task_runner.py:77} INFO - Job 3805: Subtask local_to_gcs_task
[2022-12-04 10:42:49,670] {standard_task_runner.py:52} INFO - Started process 7663 to run task
[2022-12-04 10:42:50,021] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-01T17:40:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:42:50,343] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T17:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T17:40:00+00:00
[2022-12-04 10:42:51,084] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:42:51,651] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221101T174000, start_date=20221204T104249, end_date=20221204T104251
[2022-12-04 10:42:51,779] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:42:52,028] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
