[2022-12-04 04:39:30,719] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-28T17:10:00+00:00 [queued]>
[2022-12-04 04:39:33,853] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-28T17:10:00+00:00 [queued]>
[2022-12-04 04:39:34,413] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 04:39:34,421] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 04:39:34,426] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 04:39:34,796] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-28 17:10:00+00:00
[2022-12-04 04:39:35,016] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-28T17:10:00+00:00', '--job-id', '1586', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpf5v7k_kl', '--error-file', '/tmp/tmp644c46rw']
[2022-12-04 04:39:35,059] {standard_task_runner.py:77} INFO - Job 1586: Subtask save_to_csv
[2022-12-04 04:39:34,912] {standard_task_runner.py:52} INFO - Started process 5979 to run task
[2022-12-04 04:39:36,048] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-28T17:10:00+00:00 [running]> on host 422c372562ce
[2022-12-04 04:39:36,781] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T17:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-28T17:10:00+00:00
[2022-12-04 04:39:37,203] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 04:39:39,658] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221028T171000, start_date=20221204T043930, end_date=20221204T043939
[2022-12-04 04:39:39,956] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 04:39:40,151] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
