[2022-12-04 17:40:43,994] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-10T14:00:00+00:00 [queued]>
[2022-12-04 17:40:44,011] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-10T14:00:00+00:00 [queued]>
[2022-12-04 17:40:44,011] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:40:44,012] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 17:40:44,012] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:40:44,029] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-10 14:00:00+00:00
[2022-12-04 17:40:44,035] {standard_task_runner.py:52} INFO - Started process 19562 to run task
[2022-12-04 17:40:44,040] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-10T14:00:00+00:00', '--job-id', '10792', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp94yvg10h', '--error-file', '/tmp/tmp3yvxlak9']
[2022-12-04 17:40:44,041] {standard_task_runner.py:77} INFO - Job 10792: Subtask local_to_gcs_task
[2022-12-04 17:40:44,136] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-10T14:00:00+00:00 [running]> on host 7a020590adae
[2022-12-04 17:40:44,226] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T14:00:00+00:00
[2022-12-04 17:40:45,666] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 17:40:45,682] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221110T140000, start_date=20221204T174043, end_date=20221204T174045
[2022-12-04 17:40:45,737] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 17:40:45,791] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
