[2022-12-04 03:10:37,526] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T10:20:00+00:00 [queued]>
[2022-12-04 03:10:37,591] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T10:20:00+00:00 [queued]>
[2022-12-04 03:10:37,591] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:10:37,594] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 03:10:37,599] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:10:37,767] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-27 10:20:00+00:00
[2022-12-04 03:10:37,842] {standard_task_runner.py:52} INFO - Started process 1691 to run task
[2022-12-04 03:10:37,904] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-27T10:20:00+00:00', '--job-id', '851', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpos1gtotb', '--error-file', '/tmp/tmp4_d8u98i']
[2022-12-04 03:10:37,916] {standard_task_runner.py:77} INFO - Job 851: Subtask save_to_csv
[2022-12-04 03:10:38,136] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T10:20:00+00:00 [running]> on host 422c372562ce
[2022-12-04 03:10:38,325] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T10:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T10:20:00+00:00
[2022-12-04 03:10:38,455] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 03:10:38,951] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221027T102000, start_date=20221204T031037, end_date=20221204T031038
[2022-12-04 03:10:39,078] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 03:10:39,270] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
