[2022-12-04 10:09:48,262] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-10-31T08:00:00+00:00 [queued]>
[2022-12-04 10:09:48,292] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-10-31T08:00:00+00:00 [queued]>
[2022-12-04 10:09:48,292] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:09:48,293] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:09:48,293] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:09:48,342] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_parquet> on 2022-10-31 08:00:00+00:00
[2022-12-04 10:09:48,348] {standard_task_runner.py:52} INFO - Started process 3985 to run task
[2022-12-04 10:09:48,359] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_parquet', 'scheduled__2022-10-31T08:00:00+00:00', '--job-id', '2946', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpvntbjd8c', '--error-file', '/tmp/tmpxpjcpujy']
[2022-12-04 10:09:48,363] {standard_task_runner.py:77} INFO - Job 2946: Subtask save_to_parquet
[2022-12-04 10:09:48,494] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_parquet scheduled__2022-10-31T08:00:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:09:48,605] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T08:00:00+00:00
[2022-12-04 10:09:48,849] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:09:48,869] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_parquet, execution_date=20221031T080000, start_date=20221204T100948, end_date=20221204T100948
[2022-12-04 10:09:48,937] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:09:48,997] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
