[2022-12-04 10:42:08,640] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T16:20:00+00:00 [queued]>
[2022-12-04 10:42:08,745] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T16:20:00+00:00 [queued]>
[2022-12-04 10:42:08,748] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:42:08,752] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:42:08,754] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:42:08,824] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-11-01 16:20:00+00:00
[2022-12-04 10:42:08,839] {standard_task_runner.py:52} INFO - Started process 7526 to run task
[2022-12-04 10:42:08,883] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-11-01T16:20:00+00:00', '--job-id', '3766', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpsymdmaqo', '--error-file', '/tmp/tmp1kzwiveb']
[2022-12-04 10:42:08,894] {standard_task_runner.py:77} INFO - Job 3766: Subtask save_to_csv
[2022-12-04 10:42:09,513] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T16:20:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:42:09,849] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T16:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T16:20:00+00:00
[2022-12-04 10:42:10,022] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:42:10,087] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221101T162000, start_date=20221204T104208, end_date=20221204T104210
[2022-12-04 10:42:10,221] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:42:10,752] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
