[2022-12-04 10:56:38,946] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T05:00:00+00:00 [queued]>
[2022-12-04 10:56:39,042] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T05:00:00+00:00 [queued]>
[2022-12-04 10:56:39,042] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:56:39,043] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:56:39,044] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:56:39,093] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-03 05:00:00+00:00
[2022-12-04 10:56:39,109] {standard_task_runner.py:52} INFO - Started process 10627 to run task
[2022-12-04 10:56:39,127] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-03T05:00:00+00:00', '--job-id', '4659', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpxtfkxxfp', '--error-file', '/tmp/tmp_levmwqg']
[2022-12-04 10:56:39,140] {standard_task_runner.py:77} INFO - Job 4659: Subtask local_to_gcs_task
[2022-12-04 10:56:39,318] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T05:00:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:56:39,523] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T05:00:00+00:00
[2022-12-04 10:56:40,334] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:56:40,358] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221103T050000, start_date=20221204T105638, end_date=20221204T105640
[2022-12-04 10:56:40,454] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:56:40,578] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
