[2022-12-04 14:15:56,287] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-11-08T02:00:00+00:00 [queued]>
[2022-12-04 14:15:56,349] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-11-08T02:00:00+00:00 [queued]>
[2022-12-04 14:15:56,350] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 14:15:56,351] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-12-04 14:15:56,352] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 14:15:56,429] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_parquet> on 2022-11-08 02:00:00+00:00
[2022-12-04 14:15:56,446] {standard_task_runner.py:52} INFO - Started process 8906 to run task
[2022-12-04 14:15:56,461] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_parquet', 'scheduled__2022-11-08T02:00:00+00:00', '--job-id', '8581', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpt9xxmiml', '--error-file', '/tmp/tmp5vox607d']
[2022-12-04 14:15:56,463] {standard_task_runner.py:77} INFO - Job 8581: Subtask save_to_parquet
[2022-12-04 14:15:56,830] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_parquet scheduled__2022-11-08T02:00:00+00:00 [running]> on host 7a020590adae
[2022-12-04 14:15:57,165] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T02:00:00+00:00
[2022-12-04 14:15:57,343] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 14:15:57,384] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_parquet, execution_date=20221108T020000, start_date=20221204T141556, end_date=20221204T141557
[2022-12-04 14:15:57,476] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 14:15:58,045] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
