[2022-12-04 11:00:53,491] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T16:30:00+00:00 [queued]>
[2022-12-04 11:00:53,540] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T16:30:00+00:00 [queued]>
[2022-12-04 11:00:53,540] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:00:53,541] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 11:00:53,541] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:00:53,589] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-03 16:30:00+00:00
[2022-12-04 11:00:53,607] {standard_task_runner.py:52} INFO - Started process 11557 to run task
[2022-12-04 11:00:53,633] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-03T16:30:00+00:00', '--job-id', '4931', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmph9vbc6hf', '--error-file', '/tmp/tmpvo5gswt_']
[2022-12-04 11:00:53,656] {standard_task_runner.py:77} INFO - Job 4931: Subtask local_to_gcs_task
[2022-12-04 11:00:53,845] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-03T16:30:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 11:00:54,058] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T16:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T16:30:00+00:00
[2022-12-04 11:00:54,863] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 11:00:54,878] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221103T163000, start_date=20221204T110053, end_date=20221204T110054
[2022-12-04 11:00:54,925] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 11:00:54,966] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
