[2022-12-04 10:02:20,138] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-31T06:00:00+00:00 [queued]>
[2022-12-04 10:02:20,303] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-31T06:00:00+00:00 [queued]>
[2022-12-04 10:02:20,305] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:02:20,307] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:02:20,310] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:02:20,450] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-31 06:00:00+00:00
[2022-12-04 10:02:20,523] {standard_task_runner.py:52} INFO - Started process 3502 to run task
[2022-12-04 10:02:20,570] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-31T06:00:00+00:00', '--job-id', '2867', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpokx5jdw1', '--error-file', '/tmp/tmperubnl5d']
[2022-12-04 10:02:20,583] {standard_task_runner.py:77} INFO - Job 2867: Subtask save_to_csv
[2022-12-04 10:02:21,466] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-31T06:00:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:02:22,265] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T06:00:00+00:00
[2022-12-04 10:02:22,739] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:02:24,122] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221031T060000, start_date=20221204T100220, end_date=20221204T100224
[2022-12-04 10:02:24,703] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:02:25,161] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
