[2022-12-04 11:42:53,929] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:40:00+00:00 [queued]>
[2022-12-04 11:42:54,110] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:40:00+00:00 [queued]>
[2022-12-04 11:42:54,111] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:42:54,116] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 11:42:54,119] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:42:54,212] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-11-04 18:40:00+00:00
[2022-12-04 11:42:54,241] {standard_task_runner.py:52} INFO - Started process 14259 to run task
[2022-12-04 11:42:54,310] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'local_to_gcs_task', 'scheduled__2022-11-04T18:40:00+00:00', '--job-id', '5616', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmponcltvxv', '--error-file', '/tmp/tmp8tlhk9bx']
[2022-12-04 11:42:54,322] {standard_task_runner.py:77} INFO - Job 5616: Subtask local_to_gcs_task
[2022-12-04 11:42:55,001] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.local_to_gcs_task scheduled__2022-11-04T18:40:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 11:42:55,318] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-04T18:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-04T18:40:00+00:00
[2022-12-04 11:42:56,264] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 11:42:56,544] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=local_to_gcs_task, execution_date=20221104T184000, start_date=20221204T114253, end_date=20221204T114256
[2022-12-04 11:42:56,779] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 11:42:57,112] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
