[2022-12-04 13:20:21,228] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-11-06T21:30:00+00:00 [queued]>
[2022-12-04 13:20:21,320] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_parquet scheduled__2022-11-06T21:30:00+00:00 [queued]>
[2022-12-04 13:20:21,321] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 13:20:21,327] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-12-04 13:20:21,329] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 13:20:21,397] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_parquet> on 2022-11-06 21:30:00+00:00
[2022-12-04 13:20:21,423] {standard_task_runner.py:52} INFO - Started process 3812 to run task
[2022-12-04 13:20:21,438] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_parquet', 'scheduled__2022-11-06T21:30:00+00:00', '--job-id', '7502', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpermcr759', '--error-file', '/tmp/tmpkh2mq0fx']
[2022-12-04 13:20:21,440] {standard_task_runner.py:77} INFO - Job 7502: Subtask save_to_parquet
[2022-12-04 13:20:21,652] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_parquet scheduled__2022-11-06T21:30:00+00:00 [running]> on host 7a020590adae
[2022-12-04 13:20:21,808] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T21:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-06T21:30:00+00:00
[2022-12-04 13:20:21,887] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 13:20:21,935] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_parquet, execution_date=20221106T213000, start_date=20221204T132021, end_date=20221204T132021
[2022-12-04 13:20:22,086] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 13:20:23,461] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
