[2022-12-04 12:02:29,474] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.delete_local_file scheduled__2022-11-05T13:10:00+00:00 [queued]>
[2022-12-04 12:02:29,540] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.delete_local_file scheduled__2022-11-05T13:10:00+00:00 [queued]>
[2022-12-04 12:02:29,541] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 12:02:29,542] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 12:02:29,548] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 12:02:29,599] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): delete_local_file> on 2022-11-05 13:10:00+00:00
[2022-12-04 12:02:29,612] {standard_task_runner.py:52} INFO - Started process 16597 to run task
[2022-12-04 12:02:29,626] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'delete_local_file', 'scheduled__2022-11-05T13:10:00+00:00', '--job-id', '6176', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpw05a4ljs', '--error-file', '/tmp/tmpkil1b03y']
[2022-12-04 12:02:29,628] {standard_task_runner.py:77} INFO - Job 6176: Subtask delete_local_file
[2022-12-04 12:02:29,969] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.delete_local_file scheduled__2022-11-05T13:10:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 12:02:30,593] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=delete_local_file
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T13:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T13:10:00+00:00
[2022-12-04 12:02:30,629] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 12:02:30,754] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=delete_local_file, execution_date=20221105T131000, start_date=20221204T120229, end_date=20221204T120230
[2022-12-04 12:02:30,881] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 12:02:31,117] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
