[2022-12-04 10:38:47,905] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T09:10:00+00:00 [queued]>
[2022-12-04 10:38:48,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T09:10:00+00:00 [queued]>
[2022-12-04 10:38:48,015] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:38:48,033] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:38:48,042] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:38:48,118] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-11-01 09:10:00+00:00
[2022-12-04 10:38:48,130] {standard_task_runner.py:52} INFO - Started process 6878 to run task
[2022-12-04 10:38:48,158] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-11-01T09:10:00+00:00', '--job-id', '3581', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpvjrlgxm_', '--error-file', '/tmp/tmpb32uxlh_']
[2022-12-04 10:38:48,173] {standard_task_runner.py:77} INFO - Job 3581: Subtask save_to_csv
[2022-12-04 10:38:48,536] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-11-01T09:10:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:38:48,987] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T09:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T09:10:00+00:00
[2022-12-04 10:38:49,690] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:38:49,736] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221101T091000, start_date=20221204T103847, end_date=20221204T103849
[2022-12-04 10:38:49,836] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:38:50,001] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
